# 包, 错误处理, 测试
### Package:

- 创建一个Package: cargo new mypkg
- 包含1个Cargo.toml, 它描述了如何构建这些Crates
- 只能包含0-1个library crate
- 可以包含任意数量的binary crate (从个 binary, 将入口文件放到 src/bin/下)
- 但必须至少包含一个 crate(library 或 binary)

#### Crate 的类型:
- binary: 入口文件默认为 src/main.rs; Create 名与 Package 名相同
- library: 入口文件为: src/lib.rs;Create 名与 Package 名相同

#### Crate Root:
- 是源代码文件
- Rust 编译器从这里开始, 组成你的Crate的根Module

#### Path
- 绝对路径: 从 crate root 开始, 使用 crate 名或字面值
- 相对路径: 从当前模块开始, 使用self, super 或当前模块的标识符

#### Module
- 如果 想把函数或struct等设为私有, 可以将它放到某个模块中.
- Rust 中所有的条目(函数, 方法, struct, enum, 模块,常量)默认都是私有的
- 父级模块无法访问子模块中的私有条目
- 子模块里可以使用所有祖先模块中的条目
#### 例子:

```rust
fn serve_order() {}

mod front_of_house {
    pub mod hosting {
        pub fn add_to_waitlist() {
            cook_order();
            super::super::serve_order();
        }
        fn cook_order() {}
    }
}

pub fn eat_at_restaurant() {
    crate::front_of_house::hosting::add_to_waitlist();
    front_of_house::hosting::add_to_waitlist();
}
```

#### 结构体与枚举的可见性

 - 结构体上加 `pub` 后, 字段还是私有的, 可以在字段上加 pub
- enum 枚举上加 `pub` 后, 里面的类型全部自动为 `pub`

```rust
mod back_of_house {
    pub struct Breakfast {
        pub toast: String,
        seasonal_fruit: String,
    }

    impl Breakfast {
        pub fn summer(toast: &str) -> Breakfast {
            Breakfast{
                toast: String::from(toast),
                seasonal_fruit: String::from("peaches"),
            }
        }
    }
}

pub fn eat_at_restaurant() {
    let mut meal = back_of_house::Breakfast::summer("Rye");
    meal.toast = String::from("Wheat");
}
```

####  use 习惯用法

- 函数: 将函数的父级模块引入作用域
- struct, enum,其它: 指定完整路径(指定到本身)
- 引入的模块可以加 pub 关键字导出, 使外部程序可以直接使用
- 同名条目, 引入父级  或用 as 设置别名

```rust
use crate::front_of_house::hosting;
use std::fmt::Result;
use std::io::Result as IoResult;
pub use crate:;front_of_house::hosting;
```

#### pub use 

```bash
cd rspkg
vim src/lib.rs
pub use test1::pkg1::myfunc;

vim src/main.rs
// use rspkg::test1::pkg1::myfunc;   // 如果上面没有用 pub use, 这里必须use 好多层
use rspkg::myfunc;    //上面用 pub use 导出的在多层下面的方法, 就可以在其他地方直接 use 一层就可以了
```

#### 使用外部 Package

- 编辑Cargo.toml 文件,  添加依赖包名以及版本
- cargo build (会自动到 https://crates.io 下载依赖)
- 在项目里使用 use 关键字导入包

```rust
vim Cargo.toml
[dependencies]
rand = "0.5.5"
```

#### 换国内镜像仓库

> 如果下载依赖非常慢, 可以换国内镜像仓库

```rust
ll /home/lsne/.cargo/bin/cargo
cd /home/lsne/.cargo

vim config
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"

replace-with = 'tuna'
[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[net]
git-fetch-with-cli = true
```

#### 下载完成后, 引入包

```rust
main.rs
use rand::Rng;
```

#### use 嵌套
```rust
use std::{cmp::Ordering, io};
use std::io::{self, Write};
use std::collections::*;
```

#### 模块拆分

```rust
mod front_of_house {
    pub mod hosting {
        pub fn add_to_waitlist() {
            cook_order();
            super::super::serve_order();
        }
        fn cook_order() {}
    }
}
```

#### 拆分为:

```rust
src/lib.rs
mod front_of_house;

src/front_of_house.rs
pub mod hosting;

src/front_of_house/hosting.rs
    pub fn add_to_waitlist() {
        cook_order();
        super::super::serve_order();
    }
    fn cook_order() {}

```

---
### 错误处理

#### Rust 的可靠性: 错误处理

> 大部分情况下: 在编译时提示错误, 并处理

#### 错误的分类:

> 可恢复: 如文件未找到, 可再次尝试
> 不可恢复的错误: bug, 如访问的索引超出范围

#### Rust 没有类似异常的机制

> 可恢复错误: Result<T,E>
   不可恢复: panic! 宏, 程序会立即终止运行

#### 当 panic! 宏执行:

> 你的程序会打印一个错误信息
> 展开(unwind)、清理调用栈(Stack)
> 退出程序

#### 为应对 panic, 可展开或中止(abort)调用栈

-  默认情况下, 当 panic 发生:
-  程序展开调用栈(工作量大)
    - Rust 沿着调用栈往回走
    - 清理每个遇到的函数中的数据
-  或立即中止调用栈:
    - 不进行清理，直接停止程序
    - 内存需要OS进行清理

-  想让二进制文件更小, 把设置从<展开>改为<中止>

```rust
vim Cargo.toml
[profile.release]
panic = 'abort'
```
#### RUST_BACKTRACE 环境变量

```rust
fn main() {
  panic!("出错啦啦啦");
}

windows> cargo run 
windows> set RUST_BACKTRACE=1 && cargo run  // RUST_BACKTRACE 变量可以显示panic时的回溯信息
RUST_BACKTRACE=full //会显示所有的详细信息  带有调试信息的回溯要在run或build时不指定 --release 标志
```

#### 传播错误(将错误返回给函数调用者)

> 使用  [Result 枚举](03-03-Rust-基础语法.md#标准库-Result-枚举) 做为函数返回值来将错误传播给调用者

```rust
use std::{fs::File, io::{self, Read}};

fn main() {
    let result = read_username_from_file();
}

fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");
    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();
    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```

#### 简化传播错误(问号操作符 ?)

```rust
use std::{fs::File, io::{self, Read}};

fn main() {
    let result = read_username_from_file();
}

fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}
```

#### 链式处理

```rust
use std::{fs::File, io::{self, Read}};

fn main() {
    let result = read_username_from_file();
}

fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();
    File::open("hello.txt")?.read_to_string(&mut s)?;
    Ok(s)
}
```

#### ? 与 from 函数

- 被 `?` 所应用的错误, 会隐式的被from函数处理, 进行错误类型转换
- ? 只能用于 Result, Option 和 实现了Try的类型
- `Box<dyn Error> 是trait对象, 可以简单的理解为:"任何可能的错误"`

####  何时使用panic! (编写实例，原型代码，测试)

- 演示某些概念: unwrap
- 原型代码: unwrap, expect
- 你可以确定Result 就是OK, 绝对不会出现恐慌: unwrap

#### 错误处理的指导性建议

- 当代码最终可能处于损坏状态时, 最好使用panic!
- 损坏状态(Bad state): 某些假设，保证，约定或不可变性被打破
    - 例如非法的值，矛盾的值或空缺的值被传入代码
    - 以及下列中的一条:
        - 这种损坏状态并不是预期能够偶尔发生的事情。
        - 在此之后，您的代码如果处于这种损坏状态就无法运行
        - 在您使用的类型中没有一个好的方法来将这些信息(处于损坏状态)进行编码。

#### 场景

- 调用你的代码，传入无意义的参数值: panic!
- 调用外部不可控代码, 返回非法状态, 你无法修复: panic!
- 如果失败是可放音乐的: Result
- 当你的代码对值进行操作, 首先应该验证这些值: panic!

#### 为验证创建自定义类型

```rust
pub struct  Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}", value);
        }
        Guess { value }
    }

    // 结构体里 value 字段是私有的, 所以创建函数进行访问
    pub fn value(&self) -> i32 {
        self.value
    }
}

fn main() {
 loop {
     let guess = "32";
     let gusee: i32 = match guess.trim().parse() {
         Ok(num) => num,
         Err(_) => continue,
     };
     let guess = Guess::new(guess);
 }
}
```

---
### 测试

> 运行测试请看: [Cargo测试](01-02-Cargo-使用.md#Cargo运行测试)

#### 测试标注

```rust
#[test]
```

#### 运行测试

```bash
cargo test
```

#### 测试失败的判断

> 测试函数panic!就表示失败

> 每个测试运行在一个新线程, 当主线程看到某个测试线程挂掉了，那个测试标记为失败了。

#### 测试示例

```rust
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }

    #[test]
    fn another() {
        panic!("Make this test fail");
    }
}
```

#### 标准库中常用的断言宏

> 以下三个断言宏都可以添加自定义错误信息, 自定义消息参数会被传递给 `format!` 宏

- assert! (第一个参数值必填, 自定义参数可以作为第二个参数传入)
    - `true`:  测试通过
    - `false`:  调用 panic!, 测试失败
- assert_eq! (前两个参数值必填, 自定义参数可以作为第三个参数传入)
- assert_ne! (前两个参数值必填, 自定义参数可以作为第三个参数传入)
    - eq 和 ne 实际上使用的就是 == 和 != 
    - eq 和 ne 断言失败会自动打印出两个参数的值
    - eq 和 ne 两个宏使用 debug 格式打印参数
    - eq 和 ne 要求两个参数实现了 PartialEq 和 Debug Traits (所有的基本类型和标准库里大部分类型都实现了)
    
#### 断言的使用

```rust
pub struct Rectangle {
    width: u32,
    length: u32,
}

impl Rectangle {
    pub fn can_hold(&self, other: &Rectangle) -> bool {
        self.length > other.length && self.width > other.width
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn larger_can_hold_smaller() {
        let larger = Rectangle {
            length: 8,
            width: 7,
        };
        let smaller = Rectangle {
            length: 5,
            width: 1,
        };
        assert!(larger.can_hold(&smaller));  //断言的使用
    }
}
```

#### 自定义错误

```rust
pub fn greeting(name: &str) -> String {
    format!("Hello!")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn greetings_contain_name() {
        let result = greeting("Carol");
        assert!(
            result.contains("Carol"),
            "Greeting didn't contain name, value was '{}'",
            result
        );
    }
}
```

#### 标注: should_panic 

> 该标注表示应该发生 panic。
> 可以在 should_panic 上添加可选 expected 来检查失败的消息中是否包含所指定的文字

```rust
#[test]
#[should_panic]

或者
#[test]
#[should_panic(expected = "Guess value must be between 1 and 100")]
```

```rust
pub struct Guess {
    value: u32,
}

impl Guess {
    pub fn new(value: u32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}", value)
        }
        Guess { value }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    // #[should_panic]
    #[should_panic(expected = "Guess value must be between 1 and 100")] // (expected) 部分可写可不写
    fn greater_than_100() {
        Guess::new(200);
    }
```

#### 测试中使用 `Result<T, E>`

- 函数上使用标注: `#[test]`
- 函数上不能使用标注: `#[should_panic]`
- 不能使用` assert!, assert_eq!, assert_ne! `等宏

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() -> Result<(), String> {
        if 2 + 2 == 4 {
            Ok(())
        } else {
            Err(String::from("two plus two does not equal four"))
        }
    }
}
```

#### 测试的分类

- cfg: configurateion (配置)
    - 告诉 Rust 下面的条目只有在指定的配置选项下才被包含
    - 配置选择 test: 由Rust 提供, 用来编译和运行测试。
        - 只有 cargo test 才会编译代码, 包括模块中的 helper 函数 和 `#[test]` 标注的函数
- 单元测试, 标注: `#[cfg(test)]`
    - 小, 专注
    - 一次对一个模块进行隔离测试
    - 可测试 private 接口
    - 只有运行 cargo test 才编译和运行代码
    - 运行 cargo build 则不会
- 集成测试说明
    - 在库外部。和其它处部代码一样使用你的代码
    - 只能使用 public 接口
    - 可能在每个测试中使用到多个模块
    - 在不同的目录, 不需要  `#[cfg(test)]` 标注
- 集成测试使用
    - 在 Rust 里, 集成测试完全位于被测试库的外部
    - 目的: 是测试被测试库的多个部分是否能正确的一起工作
    - 集成测试的覆盖率很重要
    - 创建集成测试: tests 目录
    - tests 目录下的每个测试文件都是单独的一个crate
        - 需要将被测试库导入
        - 无需标注 `#[cfg(test)]`, tests 目录被特殊对待
        - 只有 cargo test 时, 才会编译 tests 目录下的文件
        - 运行指定的集成测试: `cargo test <函数名>`
        - 运行某个测试文件内的所有测试: `cargo test --test <文件名>`
        - tests 目录下每个文件被编译成单独的crate, 这些文件不共享行为( 与src 下的文件规则不同)
        - 在 tests 目录的子目录中(tests/xxx/xxx.rs) 的文件不会被 crago test 视为测试文件, 可以被测试函数调用
- 如果项目是 binary crate, 只有 src/main.rs, 没有 src/lib.rs
    - 不能在 tests 目录下创建集成测试
    - 无法把 main.rs 的函数导入作用域
    - 只有 library crate 才能暴露函数给其他 crate 用
    - binary create 意味着独立运行
    - 所以 Rust 的 binary 项目, 通常会把逻辑都放到 lib.rs 里, main.rs 只是一个简单的调用


#### 示例: 将逻辑放入 `lib.rs`

```rust
src/lib.rs
tests/integration_test.rs

vim tests/integration_test.rs
use adder;

#[test]
fn it_adds_two() {
    assert_eq!(4, adder::add_two(2));
}

然后执行  cargo test
```
